const mongoose = require('mongoose');
const { Schema } = mongoose;

const AnswerSchema = new Schema({
  studentId: {
    type: Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  questionId: {
    type: String, // We'll use the unique ID generated by the frontend or mongoose for the question
    required: true
  },
  content: {
    type: String,
    required: true
  }
});

const SubmissionSchema = new Schema({
  classroomId: {
    type: Schema.Types.ObjectId,
    ref: 'Classroom',
    required: true
  },
  assessmentId: {
    type: Schema.Types.ObjectId,
    required: true
  },
  student: {
    type: Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  answers: [AnswerSchema],
  status: {
    type: String,
    enum: ['submitted', 'graded', 'pending'],
    default: 'submitted'
  },
  obtainedMarks: {
    type: Number,
    default: 0
  },
  teacherRemarks: String,
  submittedAt: {
    type: Date,
    default: Date.now
  }
}, {
  timestamps: true
});

module.exports = mongoose.model('Submission', SubmissionSchema);
